brew 'git'
brew 'youtube-dl'
brew 'wget'
brew 'nmap'
brew 'telnet'
brew 'postgresql@14'
brew 'maven'

cask 'audacity'
cask 'gimp'
cask 'postman'
cask 'spotify'
cask 'graphql-playground'
cask 'visual-studio-code'
