#!/bin/zsh

set -e

if [ ! $(which brew) ]; then
  echo "[dotfiles] Installing homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

echo "[mac-dotfiles] Installing dependencies via Homebrew..."
if brew bundle; then
  echo "[mac-dotfiles] All dependencies installed"
fi

echo "[mac-dotfiles] Linking dotfiles..."
mv $HOME/.gitconfig $HOME/.gitconfigOLD
ln -s $(pwd)/gitconfig $HOME/.gitconfig

mv $HOME/.zshrc $HOME/.zshrcOLD
ln -s $(pwd)/zshrc $HOME/.zshrc

mv $HOME/.vimrc $HOME/.vimrcOLD
ln -s $(pwd)/vimrc $HOME/.vimhrc
